---
output:
  pdf_document:
    latex_engine: xelatex
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Arial}
  - \fontsize{16pt}{18pt}\selectfont
---

 AMANA Jeanne
 
 Rue G 92 HLM Grand Dakar
 
 jeanneamana53@gmail.com

+221784628338/338251668

                                                                          
                                                                        Dakar, le 12 mars 2024



                                                                                ANSD
                                                                    Colobane Cerf-Volant Rocade Bel-Air
                                                                    A l’attention du Directeur Général




## Objet: Demande de stage

           Monsieur le Directeur Général,

Etudiante en 2e  année de formation en filière ISEP, je me permets de vous transmettre cette correspondance pour solliciter de votre part l’obtention d’un stage d’immersion de 8 semaines dans la période juillet-septembre au sein des services dont vous avez la charge.







Je dois vous signaler Monsieur le Directeur que dans le cadre de notre formation nous devons effectuer un stage obligatoire dans une structure relevant du domaine de la statistique. C’est cela qui motive ma demande. En outre, ce stage me permettra de produire un rapport dont la note de soutenance est prise en compte dans l’évaluation finale. 


Par ailleurs il sera une occasion pour moi de mettre en pratique l’ensemble des connaissances théoriques acquises à l’école, de mieux comprendre la communication dans l’entreprise et de m’exercer au travail en groupe dans vos équipes.










Tout en espérant que ma demande sera traitée avec diligence et que votre réponse sera favorable, je vous prie de bien vouloir accepter, Monsieur le Directeur Général, l’expression de ma profonde gratitude.



                                                                          l'intéressée
                                               
                                                                          ONANENA AMANA
